export const itemMap: any = {
	//账户信息
	User_nickname: "修改昵称",
	User_touxiang: "修改头像",
	User_profile: "修改个性签名",
	User_pyq_bizhi: "修改朋友圈壁纸",
	User_username: "修改微信号",
	User_sex: "修改性别",
	User_myarea: "修改我的区域",
	User_myaddress: "修改我的地址",
	User_tianjiahaoyou_yanzheng: "添加好友验证",
	User_xiangwotuijian_txy_friend: "向我推荐通讯录好友",
	User_moshengren_10_tiao: "允许陌生人看十条朋友圈",
	User_pyq_half_year: "允许朋友查看朋友圈范围-最近半年",
	User_pyq_all: "允许朋友查看朋友圈范围-全部",
	User_pyq_3_day: "允许朋友查看朋友圈范围-最近三天",
	User_pyq_notice: "朋友圈更新提醒",
	User_password_update: "修改密码",
	User_yaoyiyao_close: "开/关摇一摇",
	User_fujinren_close: "开/关附近的人",
	User_upload_screen: "截屏",
	User_clear_device: "清除设备",

	//好友
	AddFriend_count: "每天任务总次数",
	AddFriend_time_minus: "每次任务间隔时间",
	AddFriend_qun: "群添加",
	AddFriend_jiansuo: "检索添加",
	AddFriend_tongxunlu: "通讯录添加",
	AddFriend_chat: "验证好友-消息",
	AddFriend_delete: "好友验证-删除",
	AddFriend_tongguo: "好友验证-通过",
	AddFriend_add: "好友验证-添加",
	//AddFriend_add: "验证添加好友",
	//朋友圈
	Pyq_count: "每天任务总次数",
	Pyq_time_minus: "每次任务间隔时间",
	Pyq_sentshuoshuo: "发朋友圈",
	Pyq_delete: "删除我的朋友圈",
	Pyq_liulan: "浏览朋友圈",
	Pyq_dakaiyuedu: "打开阅读",
	Pyq_dianzan: "点赞",
	Pyq_zhuanfa_chat: "转发链接到聊天",
	Pyq_zhuanfa_pyq: "转发链接到朋友圈",
	Pyq_sc: "收藏",
	Pyq_comment: "评论",
	//AddFriend_tongguo: "通过好友申请",
	// Pyq_sc_text: "文字收藏",
	// Pyq_sc_pic: "图片收藏",
	// Pyq_sc_video: "视频收藏",
	// Pyq_sc_link: "链接收藏",
	Pyq_download_pic: "图片下载",
	Pyq_download_video: "视频下载",
	Pyq_share_link: "分享第三方链接",
	//公众号
	Gzh_count: "每天任务总次数",
	Gzh_time_minus: "每次任务间隔时间",
	Gzh_search: "搜索公众号",
	Gzh_guanzhu: "关注公众号",
	Gzh_guanzhu_cancel: "取消关注公众号",
	Gzh_dakaiyulan: "预览公众号",
	Gzh_yuedu: "阅读公众号文章",
	Gzh_soucang: "收藏公众号文章",
	Gzh_zhuanfa_pyq: "转发公众号文章到朋友圈",
	Gzh_zhuanfa_chat: "转发公众号文章到聊天",
	Gzh_top: "公众号置顶",
	Gzh_delete_chat: "删除聊天",
	Gzh_clear_content: "清空内容",
	//聊天设置
	ChatConfig_Sc: "聊天收藏",
	ChatConfig_AddBiaoqin: "添加聊天的表情",
	ChatConfig_RemoveBiaoqin: "移除我添加的表情",
	ChatConfig_AddPackageBiaoqin: "添加表情包商店表情包",
	ChatConfig_RemovePackageBiaoqin: "移除表情包",
	ChatConfig_One_Top: "单聊-置顶聊天",
	ChatConfig_One_Miandarao: "单聊-消息免打扰",
	ChatConfig_One_Qiangtixing: "单聊-强提醒",
	ChatConfig_One_Backpic: "单聊-设置聊天背景",
	ChatConfig_One_ClearContent: "单聊-清空聊天记录",
	ChatConfig_Group_New: "群聊-新建群聊",
	ChatConfig_Group_Addfrined: "群聊-邀请好友加群",
	ChatConfig_Group_Deletefrined: "群聊-删除群好友",
	ChatConfig_Group_NameUpdate: "群聊-修改群名称",
	ChatConfig_Group_Miandaran: "群聊-消息免打扰",
	ChatConfig_Group_Save: "群聊-保存到通讯录",
	ChatConfig_Group_ShowNickname: "群聊-显示群成员昵称",
	ChatConfig_Group_Top: "群聊-置顶群聊",
	ChatConfig_Group_Clear: "群聊-清空聊天记录",
	ChatConfig_Group_Backpic: "群聊-设置聊天背景",
	ChatConfig_Group_DeleteAndQuit: "群聊-删除并退出",
	ChatConfig_ChatOne: "单聊",
	ChatConfig_InSideScript: "内部好友聊天",
	ChatConfig_ChatOne2: "推广剧本",
	ChatConfig_ChatOne3: "内部剧本",
	ChatConfig_LookPackageBiaoqin: "浏览表情包",

	// ChatConfig_Group_New: "新建群组",
	// ChatConfig_Group_Addfrined: "邀人加入群组",
	// ChatConfig_Group_Deletefrined: "群组踢人",
	// ChatConfig_Group_New :"群组改名",
	ChatConfig_Group_MyNameUpdate: "修改我的群昵称",
	ChatConfig_QunFa: "群发",
	// ChatConfig_Delete_Message: "撤回消息",
	//收藏
	SC_add_note: "写笔记",
	SC_dakaiyulan: "打开预览收藏",
	SC_read: "阅读收藏",
	SC_delete: "删除收藏",
	SC_zhuanfa_link_pyq: "转发链接收藏到朋友圈",
	SC_zhuanfa_link_chat: "转发链接收藏到聊天",
	SC_shaixuan: "筛选收藏",
	SC_zhuanfa_note_pyq: "转发笔记到朋友圈",
	SC_zhuanfa_note_chat: "转发笔记到聊天",
	//查看好友资料
	ViewFriend_Count: "每天的总数",
	ViewFriend_Time_Minus: "间隔",
	ViewFriend_zhuye: "查看好友资料主页",
	ViewFriend_pyq: "查看好友朋友圈",
	ViewFriend_more_info: "查看更多信息",
	ViewFriend_set_star: "设为星标",
	ViewFriend_delete: "删除",
	ViewFriend_add_tag: "设置标签",

	//主体
	Gzh: "公众号",
	Pyq: "朋友圈",
	AddFriend: "加好友",
	User: "账户及隐私",
	ChatConfig: "聊天设置",
	SC: "收藏",
	ViewFriend: "查看好友资料"
};
